### PR TITLE
Move to Tailwind, Accessibility improvements, added Dark Mode

### PR DESCRIPTION
**Pull request by barrenechea**
I'm bringing this as a proposal, as it changes how styles are handled within the app. As a backend, CSS has never been my strong, but this setup highly increases my chances to do well with regards to styling and multi-resolution tweaks 😄 

<details>
  <summary>Replaced custom SASS with TailwindCSS</summary>

  I'm leveraging [Tailwind](https://tailwindcss.com/) to redo the app's styling. It has excellent community support, provides consistent experiences across all browsers, and is not opinionated about styles (such as Bootstrap, Bulma, and so on) while only bundling the required CSS classes, making the bundled CSS pretty tiny. A lot of component examples are provided online, such as [Tailwind UI](https://tailwindui.com/components), [Flowbite](https://flowbite.com/) and more.

It provides you with all regularly used CSS structures, such as `flex`, `grid`, and so on, so you can build custom UIs. I tweaked some colors to maintain a consistent gray palette across the Switches (on the Nodes tab) or the progress bar color. Also, I rounded corners for the Dialog so it more closely matches the design of the www.turingpi.com website.

  For the Switch, I replaced the `On/Off` labels with icons. I'm thinking about internationalization, and having an icon makes it much easier, as some languages may have a much higher character count for the `On/Off` labels.
  
  I also enabled [View Transitions API](https://developer.mozilla.org/en-US/docs/Web/API/View_Transitions_API) for route changes. This is a very recent feature, only supported by Chrome and Opera (WebKit is still [working on it](https://github.com/WebKit/standards-positions/issues/302)). If the browser supports it, they will see a soft transition when routes change. If they don't, they'll see no animations. I found it nice because it does not require any JS overhead to implement, as the browser handles it.
</details>

<details>
  <summary>Now using a11y-focused UI elements</summary>
  
  For most reusable UI components, I went with [Radix Primitives](https://www.radix-ui.com/primitives), which leverages the WAI-ARIA design patterns. This hugely increases compatibility with a11y features such as Screen Reader. As primitives, they are unstyled, and the "Turing styles" were applied to them.

  Also introduced Semantic HTML for improved screen reader support, with things like `<footer>` or `<main>` replacing regular `<div>`'s. Also simplified some `<div>` structures.
</details>

<details>
  <summary>Dark Mode</summary>

  Once everything was laid out, adding dark mode was pretty quick. It was just some "QA" time to ensure Lighthouse scores were 100% regarding contrast. Added an extra `logo-dark.svg` to handle the favicon so it renders appropriately based on the user's device preferences.
</details>

<details>
  <summary>Mobile Friendliness</summary>

  A few UI tweaks were also made for mobile resolutions to make it easier to use with one hand and for the content to render correctly. A new `Drawer` component is introduced, which replaces the `Dialog` on small viewports.

  I did an E2E validation of all views on the iPhone 12 Mini, iPhone 14 Pro, and iPad Pro (every device in portrait and landscape mode), applying adjustments when needed.

  I would add a navigation menu for mobile in the future so the tabs are only visible on bigger screens. It's something for my bucket list to tackle.
</details>

Also, previously, in Cooling Devices, for each step that the user moved the slider, it generated an API request, so if you moved the bar quickly back and forth, you could easily generate 100 requests in a couple of seconds. Now, it only sends a request when the user "commits a value", meaning when the user lifts the click/finger from the slider.

I bumped the version to v3.1.0 since we recently had a major version bump. I also bumped all dependencies with available updates. Let me know what you think about the versioning!

<details>
  <summary>Screenshots</summary>

  
  Lighthouse Score (checked all views):
  Screenshot 2024-05-14 at 9 46 10 AM
  SEO is 90% because I'm explicitly disallowing Robots from indexing this app. If a user ever gets to expose the UI over the internet, it will disallow it from search engine indexing.

  Info tab
  info

  Dialog vs Drawer (automatically detects device size and renders the appropriate component:
  dialog-drawer
</details>

(I promise the PR sizes will become smaller and smaller over time 🤣 this was expected to be big tho)

The last testing firmware image that I'm currently running is [this](https://github.com/barrenechea/BMC-Firmware/actions/runs/9079008885) (up-to-date, last mainline commit [BMC-installer: enable FIT image booting](https://github.com/turing-machines/BMC-Firmware/commit/04acfc865ee6a6a1bbe7f0d57ee9ba67ba649dc9))

### CODE REVIEW

**Comment by barrenechea** [comment]
Mmh, it did not fail on the build step, but rather on the step that adds a comment to the pull request reporting the build size 🤔

Maybe a GitHub Actions permissions issue? It did not happen when I tested the pipeline in my fork 😞 

**EDIT**: Ok, I replicated it. If This setting is set to Read-only, it fails:
Screenshot 2024-05-15 at 10 28 18 AM

As soon as I set it to `Read and write permissions` it can [add the comment](https://github.com/barrenechea/BMC-UI/actions/runs/9097513940):
Screenshot 2024-05-15 at 10 30 49 AM

**Comment by svenrademakers** [comment]
It looks very modern and professional! I have no experience with Tailwind or other front-end frameworks, so I'm not really able to say anything meaningful about the code. I will take it for a test spin and see if i can break it :)

I checked. I'm afraid Workflow permissions are already on read and write. I've seen similar issues before, and almost always, it was because the GITHUB_TOKEN was declared at the wrong place.

**Comment by barrenechea** [comment]
> It looks very modern and professional! I have no experience with Tailwind or other front-end frameworks, so I'm not really able to say anything meaningful about the code. I will take it for a test spin and see if i can break it :)

Thank you!! I truly put a lot of love into it 😄 

> I checked. I'm afraid Workflow permissions are already on read and write. I've seen similar issues before, and almost always, it was because the GITHUB_TOKEN was declared at the wrong place.

I found [this comment](https://github.com/peter-evans/create-or-update-comment/issues/238#issuecomment-1672346754), which explicitly states that it would not have permissions if the pull request is coming from a fork (this PR is a good example). They suggest using `pull_request_target` as the event for such cases.

That's why I didn't catch it when I tested it on my own fork, because the PRs I opened for testing were from the own repo, not forks 😞 I'll be taking a look at it!

**Comment by barrenechea** [comment]
I just cleaned up the bundle size report from the `Build` step to improve the workflow in a new PR specifically for it.

FYI, this PR's build size is `1356 KB`

**Pull request merged**
